# Generated by Django 5.0.1 on 2024-02-06 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import filter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[filter.models.Restaurent_name_should_starts_with_I])),
                ('website', models.URLField(default='')),
                ('date_opened', models.DateField()),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('logitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('Restaurent_type', models.CharField(choices=[('IN', 'INDIAN'), ('CH', 'CHINESE'), ('IT', 'ITALIAN'), ('GR', 'GREEK'), ('MX', 'MEXICAN'), ('FF', 'FASTFOOD'), ('OT', 'OTHER')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Restaurent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.restaurent')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Restaurent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter.restaurent')),
            ],
        ),
    ]
